# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
- job: JOB1
  steps:
  - script: echo job1 - hello world custom
    displayName: asdfasdf
- job: JOB2
  dependsOn: JOB1
  steps:
  - script: echo job1 - hello world custom
    displayName: asdfasdf